const palette = {
  bbq: '#910000',
  purukogi: '#FDD000',
  shio: '#00A1E9',
  tomato: '#E60013',
  wafu: '#E4007F',
  whitesauce: '#DE9D4C',
};

const pizzaMenu: Array<PizzaMenu> = [
  {
    id: 1,
    image: 'margerita.jpg',
    ingredients: ['トマトソース', 'モッツァレラ', '生バジル', 'オリーブオイル'],
    name: 'マルゲリータ',
    price: 1580,
    price_include_tax: 1738,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary: 'イタリア伝統モッツァレラと生バジルのハーモニー！',
  },
  {
    id: 2,
    image: 'pepparoni.jpg',
    ingredients: ['トマトソース', 'チーズ', 'ペパロニ'],
    name: 'ペパロニピザ',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      'ピザに欠かせないトッピングのひとつ「ペパロニ」不動の人気となることまちがいなし！！',
  },
  {
    id: 3,
    image: 'anchovy.jpg',
    ingredients: [
      'トマトソース',
      'チーズ',
      'アンチョビ',
      'オリーブ',
      'オレガノ',
      'オリーブオイル',
    ],
    name: 'アンチョビとオリーブのイタリアーナ',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary: 'アンチョビと2種類のオリーブを使った大人のピザ！！ ワインにピッタリ！！',
  },
  {
    id: 4,
    image: 'teriyaki.jpg',
    ingredients: [
      'トマトソース',
      'チーズ',
      'てりキチン',
      '玉ねぎ',
      'コーン',
      'マヨネーズ',
      'のり',
    ],
    name: 'てりやきマヨチキン',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      '甘辛く味付けしたとり肉にチーズとマヨネーズをトッピング！！ おいしくないわけがない！！',
  },
  {
    id: 9,
    image: 'ilovecheese.jpg',
    ingredients: ['モッツァレラ', 'MIXチーズ', 'カマンベール', 'パルメジャーノ'],
    name: 'I LOVE チーズ ♥',
    price: 2180,
    price_include_tax: 2398,
    sauce: null,
    summary: '4種類以上のチーズをふんだんに使ったチーズ好きのためのピザです！！',
  },
  {
    id: 10,
    image: 'bluecheese.jpg',
    ingredients: ['チーズ', 'ブルーチーズ', 'くるみ', 'はちみつ'],
    name: 'ブルーチーズとはちみつのピザ',
    price: 2180,
    price_include_tax: 2398,
    sauce: null,
    summary: 'ブルーチーズと相性のよいはちみつに、きざんだくるみをちりばめたおつまみピザ',
  },
  {
    id: 11,
    image: 'bismarck.jpg',
    ingredients: ['トマトソース', 'チーズ', '生ハム', '玉子'],
    name: '生ハムのビスマルク',
    price: 2180,
    price_include_tax: 2398,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      'ドイツを統一するために尽力した宰相ビスマルクが卵を愛したことからこの名前が！！ とろーり半熟卵。最後に生ハムをトッピング！！',
  },
  {
    id: 12,
    image: 'mentaiko.jpg',
    ingredients: ['和風ソース', 'チーズ', '明太子', 'おもち', 'コーン', 'のり'],
    name: '和風明太子もちチーズ',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.wafu,
      fg: 'white',
      name: '和風ソース',
    },
    summary:
      'たっぷり明太子におもちをのせて！ 仕上げにのりをまぶして和風テイストに仕上げました。',
  },
  {
    id: 13,
    image: 'marinara.jpg',
    ingredients: ['トマトソース', 'にんにく', 'オリーブオイル'],
    name: 'マリナーラ',
    price: 1280,
    price_include_tax: 1408,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      'マリナーラはピザ生地にトマトソースとにんにくのとってもシンプルなピザ。アクセントにオレガノで仕上げます。',
  },
  {
    id: 14,
    image: 'jarapeno.jpg',
    ingredients: ['トマトソース', 'チーズ', 'チョリソー', 'ハラペーニョ', '玉ねぎ'],
    name: 'メキシカンハラペーニョ',
    price: 1980,
    price_include_tax: 2178,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      'ハラペーニョとはメキシコ原産とする青唐辛子の一種。酢漬けにされたハラペーニョとチョリソーで Hot なピザを！!',
  },
  {
    id: 17,
    image: 'nasu-gerita.jpg',
    ingredients: ['トマトソース', 'モッツァレラ', '揚げなす'],
    name: 'なすゲリータ',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.tomato,
      fg: 'white',
      name: 'トマトソース',
    },
    summary:
      '定番マルゲリータのバジルの代わりにジューシーな、なすをトッピング！！ なすのうまみを感じてください！！',
  },
  {
    id: 18,
    image: 'bacon-potato.jpg',
    ingredients: [
      'ホワイトソース',
      '玉ねぎ',
      'チーズ',
      'ジャガイモ',
      'ベーコン',
      'マヨネーズ',
      '粒マスタード',
    ],
    name: 'ベーコンポテトピザ',
    price: 1880,
    price_include_tax: 2068,
    sauce: {
      bg: palette.whitesauce,
      fg: 'black',
      name: 'ホワイトソース',
    },
    summary:
      'ホクホクポテトにベーコンのうまみがしみこんだ満足感抜群のピザです！！ シンプルに美味しい！！',
  },
  {
    id: 19,
    image: 'ebi-remon.jpg',
    ingredients: ['ホワイトソース', 'チーズ', 'エビ', 'ズッキーニ', 'レモンソース', 'レモン'],
    name: 'エビとズッキーニのレモンピザ',
    price: 1980,
    price_include_tax: 2178,
    sauce: {
      bg: palette.whitesauce,
      fg: 'black',
      name: 'ホワイトソース',
    },
    summary:
      'プリッとしたエビとチーズをピザにしました。皮まで食べられるレモンがピザをさわやかに演出！！',
  },
  {
    id: 20,
    image: 'bulgogi.jpg',
    ingredients: ['プルコギソース', 'チーズ', '玉ねぎ', '牛肉', 'にら', 'マヨネーズ'],
    name: '韓国プルコギピザ',
    price: 2180,
    price_include_tax: 2398,
    sauce: {
      bg: palette.purukogi,
      fg: 'black',
      name: 'プルコギソース',
    },
    summary:
      'シンプルなプルコギをピザにトッピング！ 甘辛に味付けした牛肉とチーズは相性ピッタリ！！',
  },
  {
    id: 25,
    image: 'tontoro.jpg',
    ingredients: [
      '豚トロ',
      'チーズ',
      'バーベキューソース',
      'コーン',
      'パプリカ',
      'にんにく',
      'はちみつ',
    ],
    name: 'じゅわっとジューシー豚トロBBQピザ',
    price: 1980,
    price_include_tax: 2178,
    sauce: {
      bg: palette.bbq,
      fg: 'white',
      name: 'バーベキューソース',
    },
    summary:
      'コロコロした豚トロをはちみつが隠し味のバーベキューソースでピザにしました！ コーンをたっぷりのせて子供から大人まで楽しめる「気分はまさにグランピング！」なピザです！！',
  },
  {
    id: 26,
    image: 'kujonegi.jpg',
    ingredients: [
      'エビ',
      'イカ',
      'アサリ',
      'チーズ',
      '塩ダレ',
      'レモン',
      '青ネギ',
      'ごま油',
      'にんにく',
    ],
    name: '九条ネギの塩シーフードBBQピザ',
    price: 1980,
    price_include_tax: 2178,
    sauce: {
      bg: palette.shio,
      fg: 'black',
      name: '塩ダレ',
    },
    summary:
      'エビ、イカ、アサリを塩ダレでピザにしました！ネギと国産レモンをぎゅうっと絞って食べれば浜辺でバーベキューしているよう！ さっぱりした夏のピザをぜひ！',
  },
  // {
  //   id: 27,
  //   image: 'six-mushroom.jpg',
  //   ingredients: [
  //     'マッシュルームペースト',
  //     '生クリーム',
  //     'チーズ',
  //     'マッシュルーム',
  //     'マイタケ',
  //     'エリンギ',
  //     'エノキ',
  //     'シメジ',
  //     'シイタケ',
  //     'バター',
  //   ],
  //   name: '6種のきのこ達とマッシュルームデュクセルソースピザ',
  //   price: 1880,
  //   price_include_tax: 2030,
  //   sauce: null,
  //   summary:
  //     '水分を完全にとばした大量のマッシュルームを生クリームでのばすと、凝縮されたマッシュルームのいい香りがソースいっぱいに行き渡ります。そこにさらにチーズと６種のきのこ達をふんだんにのせたきのこ好きのためのきのこづくしのスペシャルピザです。',
  // },
  // {
  //   id: 28,
  //   image: 'oyster-kaki.jpg',
  //   ingredients: ['牡蠣', '柿ソース', 'チーズ', 'オイスターソース'],
  //   name: '海の牡蠣と山の柿のカキカキピザ',
  //   price: 1880,
  //   price_include_tax: 2030,
  //   sauce: null,
  //   summary:
  //     '海の物と山の物の偶然の出会い。「柿」をペーストにしてソースに使い、たっぷりのチーズと大ぶりの「牡蠣」をトッピングして焼き上げました！なかなか出会うことのない不思議な組み合わせを是非この機会にご賞味ください。',
  // },
];

export default pizzaMenu;
